# Generated by Django 4.2.6 on 2023-11-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petsapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="decription",
            new_name="description",
        ),
        migrations.AddField(
            model_name="pet",
            name="price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
