# Generated by Django 4.2.6 on 2024-01-30 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("petsapp", "0005_customer_order_shippingaddress_orderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to="petsapp.pet",
                    ),
                ),
            ],
            options={
                "db_table": "cart_items",
                "ordering": ("pet",),
            },
        ),
    ]
