# Generated by Django 4.2.6 on 2024-02-01 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "petsapp",
            "0007_alter_cartitem_options_remove_cartitem_pet_customer1_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="pet",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="petsapp.pet"
            ),
        ),
    ]
