# Generated by Django 4.2.6 on 2024-02-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petsapp", "0008_cartitem_pet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer1",
            name="phone",
        ),
        migrations.AddField(
            model_name="customer1",
            name="email",
            field=models.EmailField(default="NA", max_length=10),
        ),
    ]
