# Generated by Django 4.2.6 on 2024-02-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petsapp", "0009_remove_customer1_phone_customer1_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer1",
            name="email",
        ),
        migrations.AddField(
            model_name="customer1",
            name="username",
            field=models.CharField(default="NA", max_length=10),
        ),
    ]
